name: CI
on:
  push:
jobs:
  build:
    name: Compile
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Compile
        run: make install
  test:
    name: Test
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Install certutil on macos
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          brew install nss
      - name: Test
        run: make test
  vet:
    name: Vet
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 180s
