name: Release
on:
  push:
    tags: 'v*'
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: candy
          homebrew-tap: owenthereal/homebrew-candy
          base-branch: master
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_TOKEN }}
